name: Clash.Meta-Alpha
on:
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: metacubex/clash.meta
          ref: Alpha
      - name: Versioning
        run: |
          ##
          sudo timedatectl set-timezone "Asia/Jakarta"
          echo "NAME=clash.meta" >> $GITHUB_ENV
          BUILDTIME=$(date)
          VERSION=alpha-69-$(git rev-parse --short HEAD)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAGS=with_gvisor,with_low_memory,with_lwip" >> $GITHUB_ENV
          echo "LDFLAGS=-X 'github.com/Dreamacro/clash/constant.Version=${VERSION}' -X 'github.com/Dreamacro/clash/constant.BuildTime=${BUILDTIME}' -w -s -buildid=" >> $GITHUB_ENV
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Build Android
        run: |
          CC=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang
          CGO_ENABLED=1 CC=${CC} GOARCH=arm64 GOOS=android go build -tags ${TAGS} -trimpath -ldflags "${LDFLAGS}" -o ./${NAME}
      - name: Install UPX
        uses: crazy-max/ghaction-upx@v2
        with:
          install-only: true
      - name: Run UPX
        run: upx --best ./${NAME}
      - name: Archive
        id: archive
        run: |
          #
          GZ="${NAME}-android-arm64-${VERSION}.gz"
          tar -caf $GZ ./${NAME}
          echo "gz=$GZ" >> $GITHUB_OUTPUT
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.archive.outputs.gz }}
